# travis-ci to deploy website to FTP server using lftp
dist: trusty
language: generic
addons:
  apt:
    packages:
    - lftp
branches:
  only:
    - master
before_script:
  - chmod +x ./deploy.sh
after_success:
  - ./deploy.sh
