# travis-ci to deploy website to FTP server using ftp-deploy
dist: trusty
language: node_js
node_js:
  - "stable"
script: "true"
# branches:
#   only:
#     - master
after_success:
  - npm run deploy
