# travis-ci to deploy website to FTP server using lftp
dist: trusty
language: generic
addons:
  apt:
    packages:
    - lftp
branches:
  only:
    - master
after_success:
  - travis_retry ./deploy.sh
