dist: xenial
language: ruby
rvm:
  - 2.5.3
sudo: false

cache: bundler # caching bundler gem packages will speed up build

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - chmod +x ./scripts/proof.sh

script:
  - ./scripts/proof.sh
